production:
	gcc ./code/shift_and.h ./code/shift_and.c main.c -o exec -lm
all:
	gcc ./code/shift_and.h ./code/shift_and.c main.c -o exec -lm
clean:
	rm -r exec
analysis:
	./exec analysis
run:
	./exec run
